version: '3'

services:
  ng-presethub-bed:
    image: kromiose/ng-presethub-bed:latest
    ports:
      - "8620:8620"  # 容器的端口:主机的端口
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:  # 健康检查
      test: ["CMD", "curl", "-f", "http://localhost:8620/ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: always # 自动重启
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_HOST=host.docker.internal
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
